name: er_triage_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - joblib
  - shap
  - xgboost
  - streamlit
  - pip
  - pip:
      - streamlit-extras
